name: hao789

on:
  # schedule 部分已被删除
  workflow_dispatch: # 仅保留手动点击运行

jobs:
  run_task:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Scrape and Push
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: python hao789.py
